### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3164: character maps to <undefined>

### ISSUE THREAD

**Issue by louisXW** [HKV-products-services/hkvsobekpy#3]
I run the follow code on mac OS and get this error:
```
import hkvsobekpy as hkv
his_file = r'./test_files/CALCPNT.HIS'
calcpnt = hkv.read_his.ReadMetadata(his_file)
````
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/hkvsobekpy/io/his.py", line 450, in ReadMetadata
    self._leesAdmin(f)
  File "/anaconda3/lib/python3.7/site-packages/hkvsobekpy/io/his.py", line 214, in _leesAdmin
    param_string = f.read(self.hisFile.parameterInfo.numPar * 20).decode('windows-1252')
  File "/anaconda3/lib/python3.7/encodings/cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3164: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xiawei/Desktop/pybinary/read_with_hkv.py", line 3, in <module>
    calcpnt = hkv.read_his.ReadMetadata(his_file)
  File "/anaconda3/lib/python3.7/site-packages/hkvsobekpy/io/his.py", line 453, in ReadMetadata
    self.__errors__.administratieError()
  File "/anaconda3/lib/python3.7/site-packages/hkvsobekpy/io/his.py", line 65, in administratieError
    raise AttributeError('Administratieblok van his-file kan niet worden uitgelezen')
AttributeError: Administratieblok van his-file kan niet worden uitgelezen

Can hkvsobekpy run on mac os?

**Comment by mattijn** [comment]
Thanks for your error report. I haven't tried this package on a Mac OS. Maybe Mac OS cannot handle the requested `windows-1252` decoding?

**Comment by louisXW** [comment]
> Thanks for your error report. I haven't tried this package on a Mac OS. Maybe Mac OS cannot handle the requested `windows-1252` decoding?

I guess so. But even when I test `UTF-8` on mac there still UnicodeDecodeError. Is there a compatible decoding style works well both on Mac OS, Linux, and Windows? I guess the "Windows-1252" decoding only works on windows.

**Comment by mattijn** [comment]
All good points you mentioning. Is the described behavior appearing with multiple his-files? Can the file be read on a windows platform? 

I would like to do some tests, but couldn’t find time last days. If you could share your his-file, if it is not confidential, that would help debugging. 

After all, it also might be a wrong chosen decoding format on my side that is not capable of deciphering all type of his-files. Maybe there is not one that fits all and it should become a parameter-type like setting..

**Comment by mattijn** [comment]
I suspect your his-file contains characters that are non-existing in the ISO-8859-1 in combination with the CP1252 Windows-1252 character set

On my MacOS I can do (in a Jupyter lab notebook) the following:

```python
test_raw = 'discharge m³/s'
test_encoded = test_raw.encode('windows-1252')

print(test_encoded)
print(test_encoded.decode('windows-1252'))
```

```
b'discharge m\xb3/s'
discharge m³/s
```
